# Generated by Django 5.2.14 on 2026-05-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_twofactorcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='twofactorcode',
            new_name='accounts_tw_user_id_088dc1_idx',
            old_name='accounts_tw_user_id_4abb97_idx',
        ),
    ]
