# Generated by Django 5.2.14 on 2026-05-12 16:17

import diplomas.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiplomaSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(db_index=True, max_length=200, verbose_name="ФИО"),
                ),
                (
                    "diploma_hash",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=diplomas.models.diploma_photo_path,
                    ),
                ),
                ("photo_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["full_name"], name="diplomas_di_full_na_b020b7_idx"
                    ),
                    models.Index(
                        fields=["diploma_hash"], name="diplomas_di_diploma_9da3cc_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="diplomas_di_created_5e9772_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DiplomaPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=diplomas.models.diploma_photo_path),
                ),
                ("file_hash", models.CharField(blank=True, max_length=64, null=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="diplomas.diplomasubmission",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "indexes": [
                    models.Index(
                        fields=["submission", "order"],
                        name="diplomas_di_submiss_5b684b_idx",
                    )
                ],
            },
        ),
    ]
