# Generated by Django 5.2.14 on 2026-05-12 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'University',
                'verbose_name_plural': 'Universities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('group', models.CharField(max_length=64)),
                ('course', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='registry.university')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('speciality', models.CharField(max_length=255)),
                ('qualification', models.CharField(max_length=255)),
                ('issued_at', models.DateField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked')], default='valid', max_length=16)),
                ('qr_code_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='registry.student')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='registry.university')),
            ],
            options={
                'ordering': ('-issued_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['university', 'status'], name='registry_st_univers_6966dc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['university', 'full_name'], name='registry_st_univers_561f11_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['university', 'email'], name='registry_st_univers_5c5f4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('university', 'email'), name='unique_student_email_per_university'),
        ),
        migrations.AddIndex(
            model_name='diploma',
            index=models.Index(fields=['university', 'number'], name='registry_di_univers_639b69_idx'),
        ),
        migrations.AddIndex(
            model_name='diploma',
            index=models.Index(fields=['student'], name='registry_di_student_a70c52_idx'),
        ),
        migrations.AddConstraint(
            model_name='diploma',
            constraint=models.UniqueConstraint(fields=('university', 'number'), name='unique_diploma_number_per_university'),
        ),
    ]
