# Generated by Django 5.2.14 on 2026-05-13 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_diploma_public_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('form', 'Form'), ('public', 'Public page')], max_length=16)),
                ('requested_series', models.CharField(blank=True, max_length=64)),
                ('requested_number', models.CharField(blank=True, max_length=64)),
                ('requested_issued_at', models.DateField(blank=True, null=True)),
                ('requested_public_id', models.UUIDField(blank=True, null=True)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('revoked', 'Revoked'), ('not_found', 'Not found')], max_length=16)),
                ('verified', models.BooleanField(default=False)),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diploma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='registry.diploma')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='registry.university')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['university', '-created_at'], name='registry_di_univers_c4effb_idx'), models.Index(fields=['diploma', '-created_at'], name='registry_di_diploma_2f2684_idx'), models.Index(fields=['verification_status', '-created_at'], name='registry_di_verific_11d7c2_idx')],
            },
        ),
    ]
